modLoader="javafml"
loaderVersion="[49,)"
license="MIT"

[[mods]]
modId="spacemod"
version="1.0.0"
displayName="太空模组"
description="将Minecraft世界变为球形，实现真实的太空物理和星际旅行体验"
authors="it-is-man-i-eat"

[[dependencies.spacemod]]
modId="forge"
mandatory=true
versionRange="[47.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.spacemod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
